import { Project, TeamMember, ProjectAssignment, Language, Discipline, Company } from './types';

export const TRANSLATIONS = {
  [Language.EN]: {
    projects: "Projects",
    home: "Home",
    about: "About",
    contact: "Contact",
    search: "Search...",
    searchPlaceholder: "Search by name, job, or role...",
    enterPassword: "Enter Project Password",
    passwordPlaceholder: "Password",
    submit: "Enter",
    call: "Call",
    whatsapp: "WhatsApp",
    email: "Email",
    copy: "Copy",
    copied: "Copied!",
    noResults: "No stakeholders found.",
    filters: "Filters",
    discipline: "Discipline",
    hasWhatsapp: "Has WhatsApp",
    hasEmail: "Has Email",
    projectLocked: "Project Locked",
    projectLockedMsg: "Please enter the password to access the project directory.",
    wrongPassword: "Incorrect password. Please try again.",
    backToProjects: "Back to Projects",
    adminLogin: "Admin Login",
    dashboard: "Dashboard",
    logout: "Logout",
    active: "Active",
    completed: "Completed",
    onHold: "On Hold",
    client: "Client",
    location: "Location",
    openProject: "Open Project",
    welcomeTitle: "Project Stakeholder Directory",
    welcomeSubtitle: "Secure access to project contact information for Petrotec staff.",
    viewProjects: "View Projects",
    openMap: "Open Location",
    mainContractor: "Main Contractor",
    subContractor: "Sub Contractor",
    consultant: "Consultant",
    scope: "Scope",
    sessionExpired: "Session expired. Please login again.",
    disciplineEn: "Discipline (EN)",
    disciplineAr: "Discipline (AR)",
    addDisciplinePlaceholder: "Type and press +",
    projectDirectory: "Projects Directory",
    newProject: "New Project",
    createProject: "Create New Project",
    nameEn: "Name (EN)",
    nameAr: "Name (AR)",
    password: "Password",
    status: "Status",
    cancel: "Cancel",
    createProjectNote: "You can add details and stakeholders after creating the project.",
    edit: "Edit",
    stakeholders: "Stakeholders",
    manageTeam: "Manage Team",
    projectInfo: "Project Info",
    saveChanges: "Save Changes",
    addStakeholder: "Add Stakeholder",
    company: "Company",
    selectCompany: "-- Select Company --",
    role: "Role",
    selectRole: "-- Select Role --",
    endClient: "End Client",
    other: "Other",
    add: "Add",
    partners: "Partners",
    noPartners: "No partners added yet.",
    assignMember: "Assign Member",
    teamMembers: "Team Members",
    selectMember: "-- Select Member --",
    internal: "Internal Team",
    external: "External / Others",
    assignedTeam: "Assigned Team",
    noTeamAssigned: "No team members assigned yet.",
    adminPanel: "Admin Panel",
    clients: "Clients",
    contractors: "Contractors",
    consultants: "Consultants",
    otherMembers: "Other Members",
    backToHome: "Back to Home",
    locationEn: "Location (EN)",
    locationAr: "Location (AR)",
    mapUrl: "Map URL",
    projectScope: "Project Scope",
    projectCreatedSuccess: "Project created successfully!",
    close: "Close",
    // Team Manager
    addEmployee: "Add Employee",
    addMember: "Add Member",
    addNewEmployee: "Add New Employee",
    addNewMember: "Add New External Member",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    jobTitleEn: "Job Title (EN)",
    jobTitleAr: "Job Title (AR)",
    companyName: "Company Name",
    addToList: "Add to List",
    actions: "Actions",
    noMembersFound: "No members found.",
    // Company Manager
    manageList: "Manage your list.",
    addNew: "Add New",
    companyNameEn: "Company Name (EN)",
    companyNameAr: "Company Name (AR)",
    locationAddress: "Location / Address",
    googleMapsUrl: "Google Maps URL",
    companyLogo: "Company Logo",
    uploadImage: "Upload Image",
    uploading: "Uploading...",
    contactPersons: "Contact Persons",
    addContact: "Add Contact",
    saveCompany: "Save Company",
    keyContacts: "Key Contacts",
    more: "more",
    noFound: "No results found.",
    pending: "Pending",
    pendingApprovals: "Pending Approvals",
    approve: "Approve",
    reject: "Reject",
    suggestedBy: "Suggested for project:",
    optional: "Optional"
  },
  [Language.AR]: {
    projects: "المشاريع",
    home: "الرئيسية",
    about: "عن الشركة",
    contact: "تواصل معنا",
    search: "بحث...",
    searchPlaceholder: "ابحث بالاسم، الوظيفة، أو الدور...",
    enterPassword: "أدخل كلمة مرور المشروع",
    passwordPlaceholder: "كلمة المرور",
    submit: "دخول",
    call: "اتصال",
    whatsapp: "واتساب",
    email: "بريد إلكتروني",
    copy: "نسخ",
    copied: "تم النسخ!",
    noResults: "لم يتم العثور على نتائج.",
    filters: "تصفية",
    discipline: "التخصص",
    hasWhatsapp: "لديه واتساب",
    hasEmail: "لديه بريد إلكتروني",
    projectLocked: "المشروع مقفل",
    projectLockedMsg: "الرجاء إدخال كلمة المرور للوصول إلى دليل المشروع.",
    wrongPassword: "كلمة المرور غير صحيحة. حاول مرة أخرى.",
    backToProjects: "عودة للمشاريع",
    adminLogin: "دخول المشرف",
    dashboard: "لوحة التحكم",
    logout: "تسجيل خروج",
    active: "نشط",
    completed: "مكتمل",
    onHold: "متوقف",
    client: "العميل",
    location: "الموقع",
    openProject: "فتح المشروع",
    welcomeTitle: "دليل جهات اتصال المشروع",
    welcomeSubtitle: "وصول آمن لبيانات التواصل الخاصة بمشاريع بتروتك.",
    viewProjects: "تصفح المشاريع",
    openMap: "فتح الموقع",
    mainContractor: "المقاول العام",
    subContractor: "المقاول من الباطن",
    consultant: "الاستشاري",
    scope: "نطاق العمل",
    sessionExpired: "انتهت الجلسة. الرجاء الدخول مجدداً.",
    disciplineEn: "التخصص (EN)",
    disciplineAr: "التخصص (AR)",
    addDisciplinePlaceholder: "اكتب واضغط +",
    projectDirectory: "دليل المشاريع",
    newProject: "مشروع جديد",
    createProject: "إنشاء مشروع جديد",
    nameEn: "الاسم (EN)",
    nameAr: "الاسم (AR)",
    password: "كلمة المرور",
    status: "الحالة",
    cancel: "إلغاء",
    createProjectNote: "يمكنك إضافة التفاصيل والشركاء بعد إنشاء المشروع.",
    edit: "تعديل",
    stakeholders: "أصحاب المصلحة",
    manageTeam: "إدارة الفريق",
    projectInfo: "معلومات المشروع",
    saveChanges: "حفظ التغييرات",
    addStakeholder: "إضافة شريك",
    company: "الشركة",
    selectCompany: "-- اختر الشركة --",
    role: "الدور",
    selectRole: "-- اختر الدور --",
    endClient: "العميل النهائي",
    other: "آخر",
    add: "إضافة",
    partners: "الشركاء",
    noPartners: "لم يتم إضافة شركاء بعد.",
    assignMember: "تعيين عضو",
    teamMembers: "أعضاء الفريق",
    selectMember: "-- اختر العضو --",
    internal: "فريق داخلي",
    external: "خارجي / آخرون",
    assignedTeam: "الفريق المعين",
    noTeamAssigned: "لم يتم تعيين أعضاء للفريق بعد.",
    adminPanel: "لوحة التحكم",
    clients: "العملاء",
    contractors: "المقاولون",
    consultants: "الاستشاريون",
    otherMembers: "أعضاء آخرون",
    backToHome: "عودة للرئيسية",
    locationEn: "الموقع (EN)",
    locationAr: "الموقع (AR)",
    mapUrl: "رابط الخريطة",
    projectScope: "نطاق المشروع",
    projectCreatedSuccess: "تم إنشاء المشروع بنجاح!",
    close: "إغلاق",
    // Team Manager
    addEmployee: "إضافة موظف",
    addMember: "إضافة عضو",
    addNewEmployee: "إضافة موظف جديد",
    addNewMember: "إضافة عضو خارجي جديد",
    fullName: "الاسم الكامل",
    phoneNumber: "رقم الهاتف",
    jobTitleEn: "المسمى الوظيفي (EN)",
    jobTitleAr: "المسمى الوظيفي (AR)",
    companyName: "اسم الشركة",
    addToList: "إضافة للقائمة",
    actions: "إجراءات",
    noMembersFound: "لم يتم العثور على أعضاء.",
    // Company Manager
    manageList: "إدارة القائمة.",
    addNew: "إضافة جديد",
    companyNameEn: "اسم الشركة (EN)",
    companyNameAr: "اسم الشركة (AR)",
    locationAddress: "الموقع / العنوان",
    googleMapsUrl: "رابط خرائط جوجل",
    companyLogo: "شعار الشركة",
    uploadImage: "رفع صورة",
    uploading: "جاري الرفع...",
    contactPersons: "جهات الاتصال",
    addContact: "إضافة جهة اتصال",
    saveCompany: "حفظ الشركة",
    keyContacts: "جهات الاتصال الرئيسية",
    more: "المزيد",
    noFound: "لم يتم العثور على نتائج.",
    pending: "قيد الانتظار",
    pendingApprovals: "طلبات قيد الانتظار",
    approve: "موافقة",
    reject: "رفض",
    suggestedBy: "مقترح لمشروع:",
    optional: "اختياري"
  }
};

export const MOCK_DISCIPLINES: Discipline[] = [
    { id: 'd1', name_en: 'Management', name_ar: 'الإدارة', sort_order: 1 }
];

export const MOCK_CLIENTS: Company[] = [
    { id: 'c1', name_en: 'Cairo Electricity Production Co.', name_ar: 'شركة القاهرة لإنتاج الكهرباء', type: 'Client' },
    { id: 'c2', name_en: 'NUCA', name_ar: 'هيئة المجتمعات العمرانية', type: 'Client' },
    { id: 'c3', name_en: 'ASORC', name_ar: 'أسورك', type: 'Client' }
];

export const MOCK_CONTRACTORS: Company[] = [
    { id: 'cnt1', name_en: 'Petrotec Main', name_ar: 'بتروتك الرئيسية', type: 'Contractor' },
    { id: 'cnt2', name_en: 'Orascom Construction', name_ar: 'أوراسكوم للإنشاءات', type: 'Contractor' }
];

export const MOCK_CONSULTANTS: Company[] = [
    { id: 'cons1', name_en: 'PGESCo', name_ar: 'بجسكو', type: 'Consultant' },
    { id: 'cons2', name_en: 'Dar Al-Handasah', name_ar: 'دار الهندسة', type: 'Consultant' }
];

// Mock Data
export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    name_en: 'West Cairo Power Plant',
    name_ar: 'محطة كهرباء غرب القاهرة',
    client_en: 'Cairo Electricity Production Co.',
    client_ar: 'شركة القاهرة لإنتاج الكهرباء',
    client_id: 'c1',
    location_en: 'Giza, Egypt',
    location_ar: 'الجيزة، مصر',
    google_map_url: 'https://maps.google.com/?q=West+Cairo+Power+Plant',
    main_contractor: 'Petrotec Main',
    main_contractor_id: 'cnt1',
    consultant: 'PGESCo',
    consultant_id: 'cons1',
    scope: 'Installation of Turbine units',
    status: 'Active',
    password_hash: '123456', 
    isActive: true,
    disciplines: ['Project Management', 'Construction', 'HSE', 'QA/QC']
  },
  {
    id: 'p2',
    name_en: 'New Alamein City Towers',
    name_ar: 'أبراج مدينة العلمين الجديدة',
    client_en: 'NUCA',
    client_ar: 'هيئة المجتمعات العمرانية',
    client_id: 'c2',
    location_en: 'North Coast, Egypt',
    location_ar: 'الساحل الشمالي، مصر',
    status: 'Active',
    password_hash: 'admin',
    isActive: true,
    disciplines: ['Project Management', 'Technical Office', 'Architecture']
  },
  {
    id: 'p3',
    name_en: 'Assiut Oil Refining',
    name_ar: 'تكرير بترول أسيوط',
    client_en: 'ASORC',
    client_ar: 'أسورك',
    client_id: 'c3',
    location_en: 'Assiut, Egypt',
    location_ar: 'أسيوط، مصر',
    status: 'On Hold',
    password_hash: 'oil',
    isActive: true,
    disciplines: ['Procurement', 'Engineering']
  }
];

export const MOCK_STAKEHOLDERS: TeamMember[] = [
  { id: 's1', full_name: 'Ahmed Hassan', job_title_en: 'Project Manager', job_title_ar: 'مدير مشروع', phone: '+201001234567', whatsapp: '+201001234567', email: 'ahmed.h@petrotec.com', type: 'Internal' },
  { id: 's2', full_name: 'Mohamed Ali', job_title_en: 'Construction Manager', job_title_ar: 'مدير إنشاءات', phone: '+201223456789', whatsapp: '+201223456789', email: 'm.ali@petrotec.com', type: 'Internal' },
  { id: 's3', full_name: 'Sarah Ibrahim', job_title_en: 'Senior Architect', job_title_ar: 'مهندس معماري أول', phone: '+201112223334', email: 's.ibrahim@petrotec.com', type: 'Internal' },
  { id: 's4', full_name: 'Mahmoud Reda', job_title_en: 'Safety Officer', job_title_ar: 'مسؤول سلامة', phone: '+201098765432', whatsapp: '+201098765432', type: 'Internal' },
  { id: 's5', full_name: 'Khaled Omar', job_title_en: 'QC Engineer', job_title_ar: 'مهندس جودة', phone: '+201555555555', whatsapp: '+201555555555', email: 'k.omar@petrotec.com', type: 'Internal' },
  { id: 's6', full_name: 'External Consultant', job_title_en: 'Consultant Rep', job_title_ar: 'ممثل الاستشاري', phone: '+201999999999', type: 'External' },
];

export const MOCK_ASSIGNMENTS: ProjectAssignment[] = [
  // Project 1 Assignments
  { id: 'a1', project_id: 'p1', member_id: 's1', discipline: 'Project Management', role_en: 'Project Manager', role_ar: 'مدير المشروع', sort_order: 1 },
  { id: 'a2', project_id: 'p1', member_id: 's2', discipline: 'Construction', role_en: 'Site Manager', role_ar: 'مدير موقع', sort_order: 1 },
  { id: 'a3', project_id: 'p1', member_id: 's4', discipline: 'HSE', role_en: 'HSE Manager', role_ar: 'مدير سلامة', sort_order: 1 },
  { id: 'a4', project_id: 'p1', member_id: 's5', discipline: 'QA/QC', role_en: 'Lead QC', role_ar: 'رئيس قسم الجودة', sort_order: 1 },
  
  // Project 2 Assignments
  { id: 'a5', project_id: 'p2', member_id: 's1', discipline: 'Project Management', role_en: 'Project Director', role_ar: 'مدير مشاريع', sort_order: 1 },
  { id: 'a6', project_id: 'p2', member_id: 's3', discipline: 'Technical Office', role_en: 'Technical Manager', role_ar: 'مدير مكتب فني', sort_order: 1 },
];
